# Generated by Django 2.2.1 on 2020-01-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='register',
            name='haijin',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='last name'),
        ),
    ]
