# Generated by Django 2.2.1 on 2020-01-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200130_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='haiku_id',
            field=models.IntegerField(default=0),
        ),
    ]
