# Generated by Django 2.2.1 on 2020-01-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_register_haiku_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='haiku_id',
        ),
    ]
