# Generated by Django 2.2.1 on 2020-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_register_haiku_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='haiku_id',
            field=models.IntegerField(default=0),
        ),
    ]
